# Nixpacks configuration to prevent dual deployments
[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.build]
cmds = [
  "mv client/package.json client/package.json.bak",
  "npm install", 
  "npm run build",
  "mv client/package.json.bak client/package.json"
]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"