[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'npm ci --include=dev',
  'cd client && npm ci --include=dev'
]

[phases.build]
cmds = [
  'npm run client:install',
  'npm run client:build-only',
  'npx tsc src/simple-app.ts --outDir dist --target ES2020 --module commonjs --esModuleInterop true --allowSyntheticDefaultImports true --strict true --skipLibCheck true --resolveJsonModule true',
  'mkdir -p /app'
]

[start]
cmd = 'npm start'