[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'npm ci --include=dev',
  'cd client && npm ci --include=dev'
]

[phases.build]
cmds = [
  'npm run client:install',
  'npm run client:build-only',
  'cp -r client/dist public',
  'npx tsc src/simple-app.ts --outDir dist --target ES2020 --module commonjs --esModuleInterop true --allowSyntheticDefaultImports true --strict true --skipLibCheck true --resolveJsonModule true',
  'ls -la',
  'ls -la client/',
  'ls -la client/dist/ || echo "client/dist not found"',
  'ls -la public/ || echo "public not found"'
]

[start]
cmd = 'npm start'