[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"

# Environment variables
[deploy.env]
NODE_ENV = "production"

# Volume configuration for persistent database storage
[[deploy.volumes]]
mountPath = "/data"
name = "paintpro-database"