[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"

# Environment variables
[deploy.env]
NODE_ENV = "production"
RAILWAY_VOLUME_MOUNT_PATH = "/data"

# Volume configuration for persistent database storage
[[deploy.volumes]]
mountPath = "/data"
name = "paintpro-database"